apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
spec:
  storageClassName: fast
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/donggeollee/IdeaProjects/passmate-on-gke/dummy
    type: Directory