apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: my-redis-volume
          mountPath: /data
  volumes:
    - name: my-redis-volume
      persistentVolumeClaim:
        claimName: pv-claim-demo